/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSON, ValidateNested, IsOptional, IsString } from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { CommentCreateNestedManyWithoutArticlesInput } from "./CommentCreateNestedManyWithoutArticlesInput";
import { TagCreateNestedManyWithoutArticlesInput } from "./TagCreateNestedManyWithoutArticlesInput";
@InputType()
class ArticleCreateInput {
  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSONObject)
  body!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutArticlesInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutArticlesInput;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSONObject)
  description!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: false,
    type: () => TagCreateNestedManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => TagCreateNestedManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => TagCreateNestedManyWithoutArticlesInput, {
    nullable: true,
  })
  tags?: TagCreateNestedManyWithoutArticlesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  thumbnail!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSONObject)
  title!: InputJsonValue;
}
export { ArticleCreateInput };
