/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateToolArgs } from "./CreateToolArgs";
import { UpdateToolArgs } from "./UpdateToolArgs";
import { DeleteToolArgs } from "./DeleteToolArgs";
import { ToolFindManyArgs } from "./ToolFindManyArgs";
import { ToolFindUniqueArgs } from "./ToolFindUniqueArgs";
import { Tool } from "./Tool";
import { UserProfile } from "../../userProfile/base/UserProfile";
import { ToolService } from "../tool.service";

@graphql.Resolver(() => Tool)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ToolResolverBase {
  constructor(
    protected readonly service: ToolService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _toolsMeta(
    @graphql.Args() args: ToolFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Tool])
  async tools(@graphql.Args() args: ToolFindManyArgs): Promise<Tool[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Tool, { nullable: true })
  async tool(@graphql.Args() args: ToolFindUniqueArgs): Promise<Tool | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tool)
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "create",
    possession: "any",
  })
  async createTool(@graphql.Args() args: CreateToolArgs): Promise<Tool> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        userProfile: args.data.userProfile
          ? {
              connect: args.data.userProfile,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tool)
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "update",
    possession: "any",
  })
  async updateTool(@graphql.Args() args: UpdateToolArgs): Promise<Tool | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          userProfile: args.data.userProfile
            ? {
                connect: args.data.userProfile,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tool)
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "delete",
    possession: "any",
  })
  async deleteTool(@graphql.Args() args: DeleteToolArgs): Promise<Tool | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => UserProfile, { nullable: true })
  async userProfile(
    @graphql.Parent() parent: Tool
  ): Promise<UserProfile | null> {
    const result = await this.service.getUserProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
